version: '4.1'

services:
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express-test
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example